- hosts: all
  remote_user: $YOUR_USER
  sudo: yes

  tasks:
  - name: add $USER
    action: user name=$USER shell=/bin/bash groups=$GROUP append=yes comment="$USER_NAME" 
  - name: give keys to $USER
    authorized_key: user=$USER key="$KEY"
